apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-local-pv
spec:
  capacity:
    storage: 250Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-qdrant
  local:
    path: /var/local/qdrant-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - daggpuworker1.rdc60.lan

