apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001-nfs #PV namae
spec:
  capacity:
    storage: 20Gi # Size of Storage Volume 
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /nfs # NFS Share from exports
    server: 192.168.60.100 # NFS Server IP
  persistentVolumeReclaimPolicy: Retain

