apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-langflow-0
spec:
  capacity: 
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /home/langflow 
    server: 10.0.31.100
  persistentVolumeReclaimPolicy: Retain 
