apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-langflow-0
  namespace: langflow  # Change this to the appropriate namespace if needed
spec:
  accessModes:
    - ReadWriteMany  # Adjust based on your PV's access mode
  resources:
    requests:
      storage: 1Gi  # Adjust the size according to your PV capacity
  volumeName: data-langflow-0  # Specify the name of your existing PV
  storageClassName: ""  # Specify the NFS storage class

