apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002-nfs 
spec:
  capacity:
    storage: 250Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /home/nvidia 
    server: 10.0.31.100
  persistentVolumeReclaimPolicy: Retain 
