apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data
spec:
  capacity:
    storage: 250Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /home/webui 
    server: 10.0.31.100
  persistentVolumeReclaimPolicy: Retain 
