apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  labels:
    app: open-webui
spec:
  type: ClusterIP  # This allows external access through the node's IP
  ports:
    - port: 80          # The port that will be exposed
      targetPort: 8080    # The port on the container to forward traffic to
      protocol: TCP
      # nodePort is optional; if not specified, OpenShift will assign one automatically.
      #nodePort: 30000      # Optional: Specify a custom NodePort (within range 30000-32767)
  selector:
    app: open-webui             # Ensure this matches your deployment's labels

