apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    com.ironyun.service: ainvr-license-pvc
  name: ainvr-license-pvc
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
