apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama32nim-deployment
  namespace: nvidia-gpu-operator  # Replace with your target namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama32nim
  template:
    metadata:
      labels:
        app: llama32nim
    spec:
      nodeSelector:
        kubernetes.io/hostname: gpuworker1.psdc.lan  # Ensure it runs on the specific node
      imagePullSecrets:
      - name: nvsecret  # Reference to the created secret
      containers:
      - name: llama32nim-container
        image: nvcr.io/nim/meta/llama-3.2-11b-vision-instruct:latest
        resources:
          limits:
            nvidia.com/gpu: 1  # Request one GPU
          requests:
            nvidia.com/gpu: 1  # Request one GPU

