apiVersion: v1
kind: PersistentVolume
metadata:
  name: eyelevel-pv #PV namae
spec:
  capacity:
    storage: 250Gi # Size of Storage Volume 
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/nfs/eyelevel # NFS Share from exports
    server: 10.0.31.100 # NFS Server IP
  persistentVolumeReclaimPolicy: Retain

