apiVersion: v1
kind: PersistentVolume
metadata:
  name: eyelevel-pv2 #PV namae
spec:
  capacity:
    storage: 50Gi # Size of Storage Volume 
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/nfs/eyelevel2 # NFS Share from exports
    server: 10.0.31.100 # NFS Server IP
  persistentVolumeReclaimPolicy: Retain

