apiVersion: v1
kind: PersistentVolume
metadata:
  name: eyelevel-pv6 #PV namae
spec:
  capacity:
    storage: 20Gi # Size of Storage Volume 
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /home/nfs/eyelevel6 # NFS Share from exports
    server: 10.0.31.100 # NFS Server IP
  persistentVolumeReclaimPolicy: Retain

