apiVersion: v1
kind: PersistentVolume
metadata:
  name: ainvr-secrets-pv
  labels:
    type: local
spec:
  storageClassName: ainvr-secrets-sc
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/ainvr/secrets
